#!/bin/sh

mkdir -p /dev /proc /sys

mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys

mkdir -p /ro /rw/work /rw/root /newroot

mount -t squashfs -o loop /rootfs.squashfs /ro

mount -t overlay overlay -o lowerdir=/ro,upperdir=/rw/root,workdir=/rw/work \
    /newroot

mkdir -p /newroot/dev /newroot/proc /newroot/sys

mount --move /dev /newroot/dev
mount --move /proc /newroot/proc
mount --move /sys /newroot/sys

exec switch_root /newroot /bin/sh
