#!/bin/sh

mkdir -p /ro /rw/work /rw/root /newroot

mount -t squashfs -o loop /rootfs.squashfs /ro

mount -t overlay overlay -o lowerdir=/ro,upperdir=/rw/root,workdir=/rw/work \
    /newroot

exec switch_root /newroot /sbin/init
